### ISSUE TITLE
difference operation returns random results

### ISSUE THREAD

**Issue by dlednik** [mikedh/trimesh#1096] opened 2020-12-20 01:55 UTC
So I have 2 objects. Object A and B which represents holes I want to cut out of A.

When I run difference like below it gives me random results. Sometimes the result is A-B like expected, but sometimes it returns B-A as the result. Is this expected behaviour?
Engine in this case is blender
```
self.stl.difference(holes_elements[0], engine=self.ENGINE)
```

So this is what I expect always to get back:
![image](https://user-images.githubusercontent.com/5610466/102703406-ee96e880-42a0-11eb-81ba-cbe9ca27d39f.png)

But like I said sometimes it returns this:
![image](https://user-images.githubusercontent.com/5610466/102703413-040c1280-42a1-11eb-9a03-294f5c8ce541.png)

It cuts A from B and returns B-A as result:
![image](https://user-images.githubusercontent.com/5610466/102703424-1b4b0000-42a1-11eb-945e-6b94c383ba0f.png)

**Comment by dlednik** [comment] 2020-12-20 03:19
I made a workaround in my code for now:
https://github.com/Mambix/co2tools/blob/master/co2tools/stl/builder.py#L171

It just makes a couple of itterations and saved the result with highest mass.
No ideal, but for the size of objects I'm using is working for now.

**Comment by MarwinSc** [comment] 2020-12-29 16:29
I'm having the same problem, I tried different blender versions, but the results of the difference operation is always random.

**Comment by dlednik** [comment] 2021-01-01 03:07
I also noticed that sometimes even with the correct A-B result returned there are some holes missing in my parts. `scad` cuts them correctly, but blender misses certain cuts.

**Comment by markstor** [comment] 2021-02-05 14:46
I'm having the same issue, I think that the problem is that the order of the imported objects array is random for the new Blender versions. My guess is that Blender orders alphabetically the objects, and their names are the random tempfile names.

I couldn't find an elegant way to get a reference to the imported stl in Blender, without dealing with "blind" object selections. 
I attach a modification of the template that solved the issue for me: [modified_blender_boolean.txt](https://github.com/mikedh/trimesh/files/5933196/modified_blender_boolean.txt)

I've minimally tested in Blender versions 2.79 and 2.91 with this code:

`import sys
import time
from pathlib import Path

import trimesh
from trimesh.interfaces.blender import _blender_executable
from trimesh.util import log

blenders_dir = Path(_blender_executable).parent.parent

def test(iterations=10):
    for blender_exe in blenders_dir.rglob("blender.exe"):
        blender_version = next(blender_exe.parent.glob("*2.*")).name
        log.warning("Testing Blender {}".format(blender_version))
        _blender_executable = str(blender_exe)
        good_bools = 0
        start = time.time()
        for _ in range(iterations):  # Montecarlito
            flat_box = trimesh.primitives.creation.box((50, 50, 10))
            tall_box = trimesh.primitives.creation.box((15, 15, 20))

            donut = flat_box.difference(tall_box, engine="blender")
            # donut should be a doughnut, but it can be two boxes
            if donut.extents[0] < 49:
                log.info("Bad boolean")
            else:
                log.info("Good boolean")
                good_bools += 1
        log.warning("Blender {} succes rate {:0.2f}%. {:0.2f} seconds".format(blender_version, good_bools * 100.0 / iterations, time.time() - start))


def change_bool_script(script_path):
    from trimesh.resources import _cache
    log.warning("Changing script to {}".format(script_path))
    with open(script_path, "r") as f:
        _cache[('blender_boolean.py.template', True, False)] = f.read()


if __name__ == "__main__":
    import logging
    logging.basicConfig(level=logging.WARNING, stream=sys.stdout, format="%(message)s")

    test()
    change_bool_script(r"modified_blender_boolean.txt")
    test()
`

**Comment by markstor** [comment] 2021-02-05 14:54
I'm having the same issue, I think that problem is that the objects order in Blender is random. My guess is that the objects are alphabetically ordered, and their names are the random temporary stl files generated by trimesh.

I haven't found an elegant way to reference imported stls in Blender, without having to select "blindly" the object. I attach a modified blender template that solved the issue for me.

I've tested it minimally with Blender 2.91 and Blender 2.79 with the code below

```python
import sys
import time
from pathlib import Path

import trimesh
from trimesh.interfaces.blender import _blender_executable
from trimesh.util import log

blenders_dir = Path(_blender_executable).parent.parent

def test(iterations=10):
    for blender_exe in blenders_dir.rglob("blender.exe"):
        blender_version = next(blender_exe.parent.glob("*2.*")).name
        log.warning("Testing Blender {}".format(blender_version))
        _blender_executable = str(blender_exe)
        good_bools = 0
        start = time.time()
        for _ in range(iterations):  # Montecarlito
            flat_box = trimesh.primitives.creation.box((50, 50, 10))
            tall_box = trimesh.primitives.creation.box((15, 15, 20))

            donut = flat_box.difference(tall_box, engine="blender")
            # donut should be a doughnut, but it can be two boxes
            if donut.extents[0] < 49:
                log.info("Bad boolean")
            else:
                log.info("Good boolean")
                good_bools += 1
        log.warning("Blender {} succes rate {:0.2f}%. {:0.2f} seconds".format(blender_version, good_bools * 100.0 / iterations, time.time() - start))


def change_bool_script(script_path):
    from trimesh.resources import _cache
    log.warning("Changing script to {}".format(script_path))
    with open(script_path, "r") as f:
        _cache[('blender_boolean.py.template', True, False)] = f.read()


if __name__ == "__main__":
    import logging
    logging.basicConfig(level=logging.WARNING, stream=sys.stdout, format="%(message)s")

    test()
    change_bool_script(r"modified_blender_boolean.py.template")
    test()
```

**Comment by mikedh** [comment] 2021-04-04 01:29
I believe this was fixed by https://github.com/mikedh/trimesh/pull/1177 so closing for now.

**Closed by mikedh** 2021-04-04 01:29 UTC

**Comment by dlednik** [comment] 2021-04-05 00:58
@mikedh what version will this fix be included in?
I want to test it out with my code :)

**Comment by mikedh** [comment] 2021-04-05 01:01
It's in the latest release, if you do a `pip install --upgrade trimesh` it should get it.
