### ISSUE TITLE
How to fix non-watertight model?

### ISSUE THREAD

**Issue by LittleYuer** [mikedh/trimesh#509] opened 2019-07-24 20:37 UTC
Hi @mikedh,

Thanks for this great work.

May I ask how could I fix a non-watertight model to watertight after getting the broken faces trimesh.repair.broken_faces()?

Thanks.

**Comment by LittleYuer** [comment] 2019-07-24 20:39
Hi @mikedh,

Thanks for this great work.

May I ask how could I fix a non-watertight model after geting the broken faces trimesh.repair.broken_faces()?

Thanks.

**Comment by dbukenberger** [comment] 2019-07-25 14:08
I think the `trimeshObject.fill_holes()` method does exactly that.

**Comment by LittleYuer** [comment] 2019-07-25 14:14
Thanks for your help @dbukenberger.

After fill_holes(), i check use is_watertight(), it still returns false.

I think there is still some problems left after fill_holes(), same as results in blender.

**Comment by mikedh** [comment] 2019-07-26 19:59
Hey, yeah `mesh.fill_holes` does very simple mesh repair: if it detects a single triangle or single quad hole, it fills it in. More degenerate cases (like a vertex in the middle of an unsplit edge, larger holes, planar holes, etc) aren't handled and probably require manual repair in meshlab or blender. You can visualize broken faces like:
```
In [1]: import trimesh                                                   

In [2]: m = trimesh.creation.box()                                       

In [3]: m                                                                
Out[3]: <trimesh.base.Trimesh at 0x7f3550bc88d0>

In [4]: m.is_watertight                                                  
Out[4]: True

# slice off one face to make mesh not watertight
In [5]: m.faces = m.faces[1:]                                            

In [6]: m.is_watertight                                                  
Out[6]: False

In [7]: trimesh.repair.broken_faces?                                     
Signature: trimesh.repair.broken_faces(mesh, color=None)
Docstring:
Return the index of faces in the mesh which break the
watertight status of the mesh.

Parameters
--------------
mesh: Trimesh object
color: (4,) uint8, will set broken faces to this color
       None,       will not alter mesh colors

Returns
---------------
broken: (n, ) int, indexes of mesh.faces
File:      ~/trimesh/trimesh/repair.py
Type:      function

In [8]: broken = trimesh.repair.broken_faces(m, color=[255,0,0,255])     

In [9]: len(broken)                                                      
Out[9]: 3

In [11]: m.show(smooth=False)  
```

Which shows (toggle wireframe with `w` and culling with `c`):
![broken](https://user-images.githubusercontent.com/1403074/61978059-2c191880-afbe-11e9-9ceb-13869b3c2b7a.png)

**Comment by clbarnes** [comment] 2019-07-26 21:25
`mesh.fill_holes()` is supposed to return whether or not the resulting mesh is watertight, though, right? I'm getting this

```python
import trimesh

mesh = trimesh.load("path/to/mesh.stl")
is_watertight = mesh.fill_holes()
assert is_watertight  # fine
assert mesh.is_watertight  # AssertionError
```

**Comment by mikedh** [comment] 2019-07-27 04:08
Hey @clbarnes yeah that should really not raise. The function returns [mesh.is_watertight](https://github.com/mikedh/trimesh/blob/c006a72042fb6fcaa2ca3a6f617f3d80b3003ae0/trimesh/repair.py#L337) at the end, although there are some early exits that may be broken or possibly an error where the cache failed to dump. Could you send me a mesh that fails that check to take a look at? The following simple example passes for me:

```
    m = trimesh.creation.box()
    m.faces = m.faces[1:]

    assert not m.is_watertight
    assert m.fill_holes()
    assert m.is_watertight
```

**Comment by kajah3** [comment] 2019-08-01 17:43
I am having the exact same issue in 3.1.3.

fill_holes() returns true but running is_watertight on the mesh directly afterwards returns false. I am running it on thousands of meshes and every single time fill_holes() returns True, the mesh still isn't watertight., when I check afterwards So I am guessing this might be a caching problem because the mesh is always identical after fill_holes() as it was before when I run it in the loop.

When I try fill_holes() on a toy mesh (cube with one or two faces missing) it works as expected.

Any clue how the cache might prevent the mesh from being updated?

**Comment by mikedh** [comment] 2019-08-01 19:12
Yeah, sounds like caching. Can you send me a reproducible example?

**Comment by kajah3** [comment] 2019-08-01 19:48
I looked through the code and found the issue (in my case at least). fill_holes was exiting on line 244 after this code:
boundary_groups = group_rows(mesh.edges_sorted, require_count=1)

if len(boundary_groups) < 3:
        watertight = len(boundary_groups) == 0
        return watertight

In that case, it returns watertight=True if no edge is present only 1 time, which is different from is_watertight which checks explicitly that edges are all present twice. Inspecting my meshes, several of them have multiple "disjointed meshes" inside which happen to share some edges without having duplicate faces. In that case some edges are present 4 times which produce the strange result where the mesh is actually composed of several submeshes which are all watertight but the resulting global mesh is not watertight because some edges are used 4 times instead of 2!

I can build a quick toy example if you'd like.

**Comment by mikedh** [comment] 2019-08-04 21:58
Yeah it would be awesome if you could put together toy examples for any cases you can think of that demonstrate this! It makes it a lot easier to test a fix, and would be great to have in CI as well.

**Comment by mikedh** [comment] 2019-09-17 15:40
For some reason I can't get an example to reproduce this, but looking at the logic flow it seems like this should really be:
```
if mesh.is_watertight:
    return True
if len(boundary_groups) < 3:
    # too few edges to do any repair, and the mesh was reported as not watertight
    # since we haven't changed anything return False
    return False
```

**Comment by mikedh** [comment] 2019-09-18 16:05
Closing for now with the patch, though feel free to re-open!

**Closed by mikedh** 2019-09-18 16:05 UTC

**Comment by sharonanna** [comment] 2022-01-04 10:08
I'm getting the following error for the above check: 'AttributeError: 'TextureVisuals' object has no attribute 'face_colors''

**Comment by JaimeAbella** [comment] 2022-04-28 10:47
> I looked through the code and found the issue (in my case at least). fill_holes was exiting on line 244 after this code: boundary_groups = group_rows(mesh.edges_sorted, require_count=1)
> 
> if len(boundary_groups) < 3: watertight = len(boundary_groups) == 0 return watertight
> 
> In that case, it returns watertight=True if no edge is present only 1 time, which is different from is_watertight which checks explicitly that edges are all present twice. Inspecting my meshes, several of them have multiple "disjointed meshes" inside which happen to share some edges without having duplicate faces. In that case some edges are present 4 times which produce the strange result where the mesh is actually composed of several submeshes which are all watertight but the resulting global mesh is not watertight because some edges are used 4 times instead of 2!
> 
> I can build a quick toy example if you'd like.

How did you solve the edges that were used more than twice? Thank you!
