### ISSUE TITLE
Facets information does not include single mesh

### ISSUE THREAD

**Issue by yw259** [mikedh/trimesh#347] opened 2019-03-18 01:20 UTC
It seems that Trimesh only contains facets assembled by multiple faces. It is possible to count a single face as a facet in future?

**Comment by mikedh** [comment] 2019-03-18 16:03
Hey, not sure exactly what you mean, could you give an example? Facets are calculated through connected components of face adjacencies, and shouldn't care one way or the other about single vs multiple meshes. 

As a quick example, here's a triangulated box, the coplanar face groups (i.e. `mesh.facets`) are the pairs of triangles making up a side as expected:
```
In [1]: import trimesh

In [2]: m = trimesh.creation.box()

In [3]: m.facets
Out[3]: 
array([[ 0,  2],
       [ 1,  5],
       [ 3,  8],
       [ 4,  6],
       [ 7,  9],
       [10, 11]])

```

**Comment by yw259** [comment] 2019-03-19 17:12
Sorry for using the wrong terminology. The issue is that a single face is not recognized as a facet.
For example, if a tetrahedron is imported, Trimesh will not have any facet information relate to this tetrahedron.

**Comment by mikedh** [comment] 2019-03-19 17:26
No worries, that is by design however. We've defined `mesh.facets` as *coplanar groups of faces*, if you allowed single faces it's not really a "group of faces" and would include every face.

If that's what you wanted it's pretty straightforward to compose:
```
In [21]: mesh = trimesh.load('models/featuretype.STL')

In [22]: unincluded = np.setdiff1d(np.arange(len(mesh.faces)), np.concatenate(mesh.facets))

In [23]: unincluded.shape
Out[23]: (1588,)

In [25]: facets = mesh.facets.copy().tolist()

In [26]: facets.extend(unincluded.reshape((-1, 1)))

```

**Comment by mikedh** [comment] 2019-03-29 17:56
Closing for now, though feel free to re- open.

**Closed by mikedh** 2019-03-29 17:56 UTC

**Comment by jpmaterial** [comment] 2021-01-20 14:55
I would need the same functionality - include facets composed of one face only. The reason is that I want to process the complete surface, but it becomes much faster if I can process a facet as one. Your solution kindly provided above falls short, since I need the complete facet-infrastructure, i.e. facet_normal. Plus (as of yet non-existing) facet_adjacency TBH.
