### ISSUE TITLE
Thumbnail capture

### ISSUE THREAD

**Issue by edshkim98** [mikedh/trimesh#1105] opened 2020-12-31 03:13 UTC
Hi, I am trying to make a program to automatically capture a screenshot of each STL file.
I have found an example which I could use (https://github.com/mikedh/trimesh/blob/master/examples/offscreen_render.py),
but this doesn't seem to work on mine (Ubuntu and Jupyter notebook). My STL file is correctly imported using trimesh.load, but I get an error message saying as below:
`unable to save image Cannot connect to "None"`
Do you know any cause for this problem?
Thank you!

**Comment by mikedh** [comment] 2021-01-04 18:29
Closing as duplicate of #1112

**Closed by mikedh** 2021-01-04 18:29 UTC
